import { base } from './types/base.js';
import { signed } from './types/signed.js';
import { float } from './types/float.js';

const TYPES = { base, signed, float }, SETTINGS_KEY = 'bcp-settings', STATS_KEY = 'bcp-stats';
let active = base, settings = {}, problems = [];
const $ = selector => document.querySelector(selector);
const load = (key, fallback) => { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) : fallback; } catch { return fallback; } };
const save = (key, value) => { try { localStorage.setItem(key, JSON.stringify(value)); } catch {} };

function modeFromUrl() { const value = new URLSearchParams(location.search).get('mode'); return TYPES[value] ? value : 'base'; }
function settingsFromUrl(mode, initial) { const params = new URLSearchParams(location.search), next = { ...initial }; const keys = mode === 'base' ? ['bases', 'range', 'count'] : mode === 'signed' ? ['rep', 'width', 'format', 'count'] : ['precision', 'direction', 'format', 'count']; keys.forEach(key => { if (params.has(key)) next[key] = key === 'bases' ? params.get(key).split(',').filter(Boolean) : params.get(key); }); if (mode === 'float') { if (params.has('split')) next.split = params.get('split') === 'true'; if (params.has('special')) next.special = params.get('special') === 'true'; } return next; }
function modeSettings(mode) { const all = load(SETTINGS_KEY, {}); return { ...TYPES[mode].defaults, ...(all[mode] || {}) }; }
function renderOptions() { $('#modeOptions').innerHTML = active.renderOptions(settings); }
function saveCurrent() { settings = active.readOptions($('#modeOptions')); const all = load(SETTINGS_KEY, {}); all[active.id] = settings; save(SETTINGS_KEY, all); }
function configure(mode, fromUrl = false) { active = TYPES[mode] || base; settings = fromUrl ? settingsFromUrl(mode, modeSettings(mode)) : modeSettings(mode); $('#mode').value = active.id; renderOptions(); }
function migrateStats() { const stats = load(STATS_KEY, {}), migrated = { ...stats }; Object.keys(stats).filter(key => !key.includes(':')).forEach(key => { migrated[`base:${key}`] = stats[key]; delete migrated[key]; }); save(STATS_KEY, migrated); }
function generate() { saveCurrent(); if (active.id === 'base' && settings.bases.length < 2) { $('#warn').textContent = 'Select at least two bases to convert between.'; return; } $('#warn').textContent = ''; problems = active.generate(settings, Number(settings.count)); render(); }
function render() { const sheet = $('#sheet'); sheet.innerHTML = ''; problems.forEach((problem, index) => { const prompt = active.prompt(problem), item = document.createElement('li'); item.className = 'prob'; const fields = prompt.fields ? `<span class="split-fields">${prompt.fields.map(label => `<label><span>${label}</span><input class="answer-field" inputmode="text" autocomplete="off" autocapitalize="characters" spellcheck="false"></label>`).join('')}</span>` : '<input class="answer-field" inputmode="' + prompt.inputmode + '" autocomplete="off" autocapitalize="characters" spellcheck="false">'; item.innerHTML = `<span class="num">${index + 1}</span><div class="q"><span class="val">${prompt.valueHtml}</span><span class="dir">${prompt.directionText}</span></div><label class="ans"><span class="sr">Problem ${index + 1} answer: ${prompt.answerLabel}</span>${fields}</label><div class="below"><span class="result" aria-live="polite"></span><button class="worklink" aria-expanded="false">Show work</button><a class="learnlink" href="./learn.html#${active.id}">Learn how</a></div><div class="work" hidden></div>`; const inputs = [...item.querySelectorAll('.answer-field')]; inputs.forEach(input => { input.addEventListener('keydown', event => { if (event.key === 'Enter') { event.preventDefault(); checkOne(index); updateScore(); sheet.children[index + 1]?.querySelector('input')?.focus(); } }); input.addEventListener('input', () => { inputs.forEach(field => field.classList.remove('ok', 'bad')); item.querySelector('.result').textContent = ''; }); }); item.querySelector('.worklink').addEventListener('click', event => { const work = item.querySelector('.work'), open = work.hidden; if (open) work.innerHTML = active.work(problem); work.hidden = !open; event.target.textContent = open ? 'Hide work' : 'Show work'; event.target.setAttribute('aria-expanded', String(open)); }); sheet.appendChild(item); }); $('#score').textContent = ''; $('#key ol').innerHTML = problems.map(problem => `<li>${active.prompt(problem).valueHtml} = ${active.answer(problem)}</li>`).join(''); }
function checkOne(index, reveal = false) { const problem = problems[index], item = $('#sheet').children[index], inputs = [...item.querySelectorAll('.answer-field')], input = inputs[0], result = item.querySelector('.result'), value = inputs.length > 1 ? inputs.map(field => field.value).join('|') : input.value; let outcome = active.check(problem, value); if (reveal && outcome.status === 'empty') { outcome = { status: 'wrong', message: `Answer: ${active.answer(problem)}` }; } inputs.forEach(field => field.classList.remove('ok', 'bad')); if (outcome.status === 'empty') return; inputs.forEach(field => field.classList.add(outcome.status === 'correct' ? 'ok' : 'bad')); result.className = `result ${outcome.status === 'correct' ? 'ok' : 'bad'}`; result.textContent = outcome.message; record(problem, outcome.status === 'correct'); }
function updateScore() { let right = 0, tried = 0; [...$('#sheet').children].forEach(item => { const input = item.querySelector('.answer-field'); if (input.classList.contains('ok')) { right++; tried++; } else if (input.classList.contains('bad')) tried++; }); $('#score').textContent = tried ? `${right} of ${problems.length} correct` : ''; }
function record(problem, correct) { if (problem.graded) return; problem.graded = true; const stats = load(STATS_KEY, {}), key = `${active.id}:${active.statKey(problem)}`, current = stats[key] || { right: 0, total: 0 }; current.total++; if (correct) current.right++; stats[key] = current; save(STATS_KEY, stats); renderStats(); }
function renderStats() { const stats = load(STATS_KEY, {}), groups = {}; Object.entries(stats).forEach(([key, value]) => { const [mode, statKey] = key.includes(':') ? key.split(/:(.*)/s) : ['base', key]; (groups[mode] ||= []).push([statKey, value]); }); const rows = Object.entries(groups).flatMap(([mode, entries]) => [`<tr class="group"><th colspan="4">${TYPES[mode]?.label || mode}</th></tr>`, ...entries.map(([key, value]) => `<tr><td>${TYPES[mode]?.statLabel(key) || key}</td><td>${value.right}</td><td>${value.total}</td><td>${Math.round(value.right / value.total * 100)}%</td></tr>`)]); $('#stats tbody').innerHTML = rows.length ? rows.join('') : '<tr><td class="empty" colspan="4">Check some answers and your accuracy by type shows up here.</td></tr>'; }
function buildRef() { $('#ref tbody').innerHTML = Array.from({ length: 16 }, (_, value) => `<tr><td>${value}</td><td>${value.toString(2).padStart(4, '0')}</td><td>${value.toString(8)}</td><td>${value.toString(16).toUpperCase()}</td></tr>`).join(''); }

migrateStats();
$('#mode').addEventListener('change', event => { configure(event.target.value); generate(); });
$('#modeOptions').addEventListener('change', saveCurrent);
$('#newBtn').addEventListener('click', generate);
$('#checkBtn').addEventListener('click', () => { problems.forEach((_, index) => checkOne(index)); updateScore(); });
$('#revealBtn').addEventListener('click', () => { problems.forEach((_, index) => checkOne(index, true)); updateScore(); });
$('#printBtn').addEventListener('click', () => window.print());
$('#resetStats').addEventListener('click', () => { if (confirm('Reset all accuracy stats on this device?')) { save(STATS_KEY, {}); renderStats(); } });
configure(modeFromUrl(), true); buildRef(); renderStats(); generate();
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js').catch(() => {}));
